services:
    reverse-proxy:
        image: traefik:v3.3
        container_name: reverse_proxy
        command:
            - "--api.insecure=true"
            - "--providers.docker"
            - "--accesslog=true"
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    rabbitmq:
        image: rabbitmq:management-alpine
        container_name: rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        
    
include:
    - path: ./auth/docker-compose.yml
    - path: ./events/docker-compose.yml
    - path: ./orders/docker-compose.yml