# version: "3.8"

services:
    auth:
        container_name: auth
        build: ./auth
        ports:
            - "8000:8000"
        depends_on:
            - mongodb

    mongodb:
        image: mongo:latest
        container_name: auth_db
        restart: always
        env_file: ./auth/.env
        ports:
            - "${DB_PORT:-27017}:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - my_db_data:/data/db

    reverse-proxy:
        image: traefik:v3.3
        command:
            - "--api.insecure=true"
            - "--providers.docker"
            - "--accesslog=true"
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    nginx:
        image: nginx:latest
        container_name: nginx_protected
        volumes:
            - ./nginx:/usr/share/nginx/html 
        labels:
            - "traefik.http.routers.nginx.rule=Host(`localhost`)"
            - "traefik.http.services.nginx.loadbalancer.server.port=80"
            - "traefik.http.middlewares.auth-mv.forwardauth.address=http://auth:8000/"
            - "traefik.http.routers.nginx.middlewares=auth-mv@docker"


volumes:
    my_db_data:
